universe = vanilla
executable = knn.sh
arguments = $(time)
transfer_input_files = knn.py, /home/groups/STAT_DSCP/group9/data/$(time).csv
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
output = knn_$(time).out
error = knn$(time).err
log = knn$(time).log
request_cpus = 4
request_memory = 5GB
request_disk = 10GB

container_image = osdf:///ospool/uc-shared/public/OSG-Staff/xalim_stat/python_numpy_pandas_sklearn.sif

queue time from formatted_list.txt
